### ISSUE TITLE
researching rules

### ISSUE THREAD

**Issue by Onslow-DM** [OnslowCollege/complex-techniques-rja-2024-daniel-dylan-kellan#2]

**Comment by Onslow-DM** [comment]
rules:
must turn over/capture a piece
if not able to play then skip turn
win if:
person with most pieces when board is full
if no more of your pieces are on the board

**Comment by KellanVK** [comment]
To make a move, you must pick a point pointing from your own tile directly through an opponents tile/s either horizontally, vertically or diagonally. This will result in all the opponent's tiles in that path being flipped over.
